apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: bluegreen
  name: bluegreen-pipeline
spec:
  source:
    git:
      uri: http://10.1.2.2:3000/tislam/bluegreen
      ref: pipeline-stages
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline